AWSTemplateFormatVersion: '2010-09-09'
Description: This deploys an Automation Document that builds a .Net Framework Container that includes msbuild (qs-1qh1429dt)
Parameters:
  CredSpecBucket:
    Description: "S3 bucket where the CredSpec File will be saved."
    Type: "String"
  DomainDNSName:
    Description: "Domain DNS Name used to join Active Directory in order to perform gMSA configuration."
    Type: "String"
  GroupManagedServiceAccountName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: gMSASample
    Description: The first group Managed Service Account used with the Cluster, this will create and AD Group of the same name.
    MaxLength: '25'
    MinLength: '1'
    Type: String
  DomainSecretsArn:
    Description: "The Secrets Manager name or ARN that will be used to perform all need domain actions."
    Type: "String"
  gMSAExecuteArn:
    Description: ARN for Lambda that executes SSM Automation Document.
    Type: String
  gMSAAutomationRoleArn:
    Description: ARN for role for gMSA role.
    Type: String
  gMSADocumentName:
    Description: Name of AWS Systems Manager Document that configured gMSA.
    Type: String
  InstanceProfile:
    Description: "Instance profile that has a role that allows EC2 Instance to grab secrets from Secrets Manager
       and interact with AWS Systems Manager"
    Type: "String"
  DomainMemberSGID:
    Description: ID of the domain member security group (e.g., sg-7f16e910).
    Type: String
    #Type: AWS::EC2::SecurityGroup::Id
  SubnetId:
    Description: "Subnet ID that give the ability to communicate to Active Directoy"
    Type: "String"
Resources:
  ExecuteSSMAutomation:
    Type: Custom::ExecuteSSMAutomation
    Properties:
      ServiceToken: !Ref gMSAExecuteArn
      DocumentName: !Ref gMSADocumentName
      CredSpecBucket: !Ref CredSpecBucket
      DomainDNSName: !Ref DomainDNSName
      ServiceAccount: !Ref GroupManagedServiceAccountName
      DomainSecretsArn: !Ref DomainSecretsArn
      InstanceProfile: !Ref InstanceProfile
      SecurityGroupId: !Ref DomainMemberSGID
      SubnetId: !Ref SubnetId
      StackName: !Ref AWS::StackName
      AutomationAssumeRole: !Ref gMSAAutomationRoleArn
  SSMWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  SSMWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
        Count: 1
    DependsOn:
      - ExecuteSSMAutomation
    Properties:
      Handle:
        Ref: "SSMWaitHandle"
      Timeout: "3600"
      Count: 1
